Added Javascript Challenges
DSC-SIST/D-Bug pull request #12
Opened 2020-10-20 12:32 UTC by HarshCasper

### Have you read the Contributing Guidelines on Pull Requests?

Yes

### Description

Added Javascript Challenges from `Question_1` to `Question_10`.

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` according to the changes I have made.

2020-10-20 12:35 UTC, AkashM398 approved these changes

2020-10-20 13:01 UTC, KamalDGRT commented on JavaScript/Question_02/question_02.js
> +console.log(filteredArray([[3, 2, 3], [1, 6, 3], [3, 13, 26], [19, 3, 9]], 3));
Kindly add a new line character at the end of this file.

2020-10-20 13:02 UTC, KamalDGRT commented on JavaScript/Question_03/README.md
> +Given a Number `n` implement Recursion to create a COuntdown Timer.
Change "COuntdown" to "Countdown"

2020-10-20 13:03 UTC, KamalDGRT commented on JavaScript/Question_03/question_03.js
> +console.log(countdown(5));
Add a new line character to represent End-Of-File.

2020-10-20 13:15 UTC, KamalDGRT requested changes
### Kindly do the following changes :

- Change the spelling in README.md of question_03.js file.
- Add a new line to denote the EOF in the following files : 
  - question_02.js
  - question_03.js
  - question_04.js
  - question_05.js
  - question_07.js
  - question_08.js
  - question_09.js
  - question_10.js
- Remove the extra blank line in these files. (Line number 5)
  - README.md of question 7
  - README.md of question 9

2020-10-21 04:11 UTC, HarshCasper commented
Made Changes to the Files. I am merging them now.

2020-10-21 04:11 UTC, merged