11th to 20th Python Questions
DSC-SIST/D-Bug pull request #2
Opened 2020-10-12 04:38 UTC by snehagupta-4

Added 11th to 20th Python Questions. Please inform me if any changes are required.

2020-10-12 06:14 UTC, HarshCasper requested changes
Here are a few points: 

- Remove all the Questions from GeeksforGeeks/Hackerrank/LeetCode 
- Run your Code through PyLint and configure your Code to make it readable 
- Rename all Markdown Files as `README.md` and keep the File Names consistent. 
- Avoid Spell Mistakes.

2020-10-12 06:14 UTC, HarshCasper commented on Python/Question_11/Alphabet Rangoli.md
> +#Question
Rename the File as `Alphabet_Rangoli` rather than `Alphabet Rangoli`

2020-10-12 06:14 UTC, HarshCasper commented on Python/Question_11/Alphabet Rangoli.py
> +n = int(input()
Run the Code through PyLint. Keep the Variable Names meaningful.

2020-10-12 06:14 UTC, HarshCasper commented on Python/Question_12/Pattern.md
> +
Remove these extra lines in the Markdown File

2020-10-12 06:14 UTC, HarshCasper commented on Python/Question_12/Pattern.py
> +
Remove these Extra Lines of Code. They seem to be redundant

2020-10-12 06:14 UTC, HarshCasper commented on Python/Question_14/Maximum Special Sum.md
> +Consider the subarray {14, 2, 7}
Use: 

- List 1
- List 2
- List 3 

to denote Bullet Points

2020-10-12 06:14 UTC, HarshCasper commented on Python/Question_20/Validating emial address.md
> +#Question
Change the Name of the File. Keep apt underscores and work on the Spell Mistakes

2020-10-12 06:14 UTC, HarshCasper commented on Python/Question_20/Validating emial address.md
> +['brian-23@hackerrank.com', 'britts_54@hackerrank.com', 'lara@hackerrank.com']
Seems you have picked the question from Hackerrank. Try to make your own questions rather than picking them from Third Party Websites.

2020-10-12 06:14 UTC, HarshCasper commented on Python/Question_18/Sudoko.md
> +Given a partially filled 9×9 2D array ‘grid[9][9]’, the goal is to assign digits (from 1 to 9) to the empty cells so that every row, column, and subgrid of size 3×3 contains exactly one instance of t
This Question forms part of the BackTracking Article Series by GeeksforGeeks. It's best to remove the Question as well as the Code.

2020-10-19 18:28 UTC, snehagupta-4 commented
> Here are a few points:
> 
> * Remove all the Questions from GeeksforGeeks/Hackerrank/LeetCode
> * Run your Code through PyLint and configure your Code to make it readable
> * Rename all Markdown Files as `README.md` and keep the File Names consistent.
> * Avoid Spell Mistakes.

I lost all the changes on my local PC. So I've created a new PR. Please check.

2020-10-20 07:13 UTC, closed without merging